import Challenger from '../components/Hero/Challenger.png';

export const carList = [
    {
        id: 1,
        name: 'Challenger',
        price: '$800',
        brand: 'Ferrari',
        image: Challenger,
        available: true,
    },
    {
        id: 2,
        name: 'Challenger',
        price: '$800',
        brand: 'Dodge',
        image: Challenger,
        available: true,
    },
    {
        id: 3,
        name: 'Challenger',
        price: '$800',
        brand: 'BMW',
        image: Challenger,
        available: true,
    },
    {
        id: 4,
        name: 'Challenger',
        price: '$800',
        brand: 'Dodge',
        image: Challenger,
        available: false,
    },
    {
        id: 5,
        name: 'Challenger',
        price: '$800',
        brand: 'Dodge',
        image: Challenger,
        available: false,
    },
    {
        id: 6,
        name: 'Challenger',
        price: '$800',
        brand: 'BMW',
        image: Challenger,
        available: true,
    },
    {
        id: 7,
        name: 'Challenger',
        price: '$800',
        brand: 'Dodge',
        image: Challenger,
        available: false,
    },
    {
        id: 8,
        name: 'Challenger',
        price: '$800',
        brand: 'Ford',
        image: Challenger,
        available: true,
    },
    {
        id: 9,
        name: 'Challenger',
        price: '$800',
        brand: 'Ford',
        image: Challenger,
        available: false,
    },
]